name: PR Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  print-messages:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Print Environment Variable
      env:
        GREETING: "Hello from GitHub Actions!"
      run: |
        echo "Environment Variable Message: $GREETING"
        
    - name: Print Secret
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
      run: |
        echo "Secret Message: $MY_SECRET"
